### ISSUE TITLE
Stand-alone exiftool

### ISSUE THREAD

**Issue by veewee** [alchemy-fr/exiftool#5]
Hello,

Is it possible to remove the requirement to "phpexiftool/phpexiftool" in the composer file.
This package is a dependency of the phpexiftool package. It does not need the phpexiftool package to function.

By removing that requirement, this project could be used stand-alone.

Thanks!

**Comment by tanakahisateru** [comment]
It's the same idea which I have!

**Comment by bburnichon** [comment]
In case it is still needed, I just upgraded exiftool version and removed requirement.

**Comment by veewee** [comment]
Thanks!
